"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$conda\
$character\
"""

right_format = """\
$conda\
$time\
"""

add_newline = false

[directory]
truncation_length = 2
truncate_to_repo = false
fish_style_pwd_dir_length = 2
truncation_symbol = "…/"
style = "blue"

[character]
success_symbol = " [❯](purple)"
error_symbol = " [❯](red)"
vimcmd_symbol = " [❮](green)"

[line_break]
disabled = true

[git_commit]
tag_symbol = " tag "

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = """[(\
[$conflicted](red)\
[$untracked](grey)\
[$modified](purple)\
[$staged](yellow)\
[$renamed](purple)\
[$deleted](purple)\
[$ahead_behind](green)\
[$stashed](blue)\
)]($style)\
"""
# style = "cyan"
conflicted = " =$count"
untracked = " ?$count"
modified = " !$count"
staged = " *$count"
stashed = " ≡$count"
ahead = " ⇡$count"
behind = " ⇣$count"
renamed = " r$count"
deleted = " x$count"
diverged = " ⇡$ahead_count ⇣$behind_hount"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
show_milliseconds = true
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[conda]
format = '$symbol[$environment]($style)'
symbol = "py "
style = "dimmed green"

[time]
disabled = false
